### ISSUE TITLE
התקנת לינט

### ISSUE THREAD

**Issue by wottem** [adam2314/linet3#610]
שלום. 
באחרונה ניסיתי להתקין את התוכנה על שרת redhat (ראשית תודה על ההשקעה הרבה). 
בהתקנה היו מספר בעיות:
1. ה-composer לא התקין את כל הקבצים במקום הנכון:
   * קבצים שהיו צריכים להיות בתקיית bower הגיעו ל-bower-asset, למשל.
   * class בשם "adam/EavBehavior" לא נמצאה (כתוצאה מכך מספר רב של הודעות שגיאה). 

2. בעיה לא ברורה בהעלאת קבצים (בניסיון להעלות תמונת לוגו למשל, כאילו לא קורה שום דבר, לא נמצא בלוגים). 
המון תודות

**Comment by dan-omniscience** [comment]
+1
the bower files that I needed to move from bower-assets to bower directory are "bootstrap" and "yii2-pjax"

another issue for me was that the installer is creating some of the DB tables in "latin1_swedish_ci" instead of "utf8_general_ci"

**Comment by adam2314** [comment]
in the latest commit i added in the extra part of the composer.json 
```javascript
   "npm-asset-library": "vendor/npm",
   "bower-asset-library": "vendor/bower"
'''
which should cover the bower issue.
EavBehavior class has been addressed before by the autoload(psr-4) entry (the same file).
Dan when you create a database it must be set to UTF8 defaults or will have issues with Hebrew.
i'm living this issue open for updates from you.

**Comment by dan-omniscience** [comment]
Hey Adam,
I did another install test and the fix for the paths still not complete,
linet is looking for bootstrap at: protected/vendor/bower/bootstrap/dist
and the composer is installing it at: protected/vendor/bower/bower-asset/bootstrap/

**Comment by adam2314** [comment]
did you start from a new git clone? its not Linet its the yii framework

**Comment by dan-omniscience** [comment]
yes

**Comment by dan-omniscience** [comment]
In regard to the db charset, it is working fine if the db is set in advance to utf8 but I think that it can also be set in the php installer so this would not be an issue

**Comment by adam2314** [comment]
i think it is OK now notice i've updated the readme

**Comment by wottem** [comment]
The composer is still not putting the files in the right place (it puts them in bower/bower-assets/... and not in bower/. 
The EavBehaviur class issue is OK now.

**Comment by adam2314** [comment]
@wottem run composer update again

**Comment by adam2314** [comment]
update?

**Comment by asafo** [comment]
I've also tried the normal sequence:

1. clone linet
2. install composer locally
3. ./composer.phar update


This works, but installs yii2 : 2.0.0-beta,
 which will not run Linet3 (e.g: no csrfMetaTags() function in Yii\helpers\BaseHtml)

The reason it installs 2.0.0-beta is because all later versions requires bower/assets things,
Which was suppused to be handled by  "fxp/composer-asset-plugin":"*",
Still checking on this

**Comment by asafo** [comment]
upgrading from yii 2.0.0-beta to 2.0.6:
add:
"fxp/composer-asset-plugin":"~1.1.1"
run ./composer.phar update
change   "yiisoft/yii2": "*" to "yiisoft/yii2": "2.0.6"
run ./composer.phar update
